name = "PINControlSystem"
uuid = "09874115-f1ab-4b14-b09a-366d65825eb6"
authors = ["taeho <virtalf@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DimensionfulAngles = "2d4b8d7a-02d9-40f9-9abe-9c695b77de0d"
PI5_LG_IO = "5fd6ec1f-d545-475a-9735-234e8bedae5e"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
BenchmarkTools = "1.6.0"
Blink = "0.12.9"
CSV = "0.10.15"
DataFrames = "1.7.0"
DataFramesMeta = "0.15.4"
DimensionfulAngles = "0.2.1"
PI5_LG_IO = "1.0.0"
PlotlyJS = "0.18.15"
Plots = "1.40.9"
Query = "1.0.0"
Revise = "3.7.2"
StaticArrays = "1.9.12"
Unitful = "1.22.0"
